version: '3.8'

services:
  bot:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    working_dir: /app
    ports:
      - 80:3000

  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      
volumes:
  mongodb: