name: Deploy to Production Environment
on:
  push:
    branches:
      - 'DEGEN'
jobs:
  deploy-prod:
    environment:
      name: production
      url: https://app.logdna.com/273e532689/logs/view?apps=degen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Run test cases
        run: yarn test --watchAll=false
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'degen-poap'
          heroku_email: 'bankless@nonsensecodes.io'
          procfile: 'worker: yarn prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.PROD_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.PROD_BOT_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.PROD_BOT_APPLICATION_ID}}
          HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
          HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
          HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
          HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
          HD_NOTION_TOKEN: ${{secrets.PROD_NOTION_TOKEN}}
          HD_LOGDNA_TOKEN: ${{secrets.PROD_LOGDNA_TOKEN}}
          HD_TWITTER_API_TOKEN: ${{secrets.PROD_TWITTER_API_TOKEN}}
          HD_TWITTER_API_SECRET: ${{secrets.PROD_TWITTER_API_SECRET}}
          HD_TWITTER_BEARER_TOKEN: ${{secrets.PROD_TWITTER_API_BEARER_TOKEN}}
          HD_TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.PROD_TWITTER_API_ACCESS_TOKEN_SECRET}}
          HD_DD_API_KEY: ${{secrets.PROD_DATADOG_API_KEY}}
          HD_POAP_DOMAIN: ${{secrets.PROD_POAP_DOMAIN}}
          HD_POAP_AUDIENCE: ${{secrets.PROD_POAP_AUDIENCE}}
          HD_POAP_CLIENT_ID: ${{secrets.PROD_POAP_CLIENT_ID}}
          HD_POAP_CLIENT_SECRET: ${{secrets.PROD_POAP_CLIENT_SECRET}}
          
