name: Deploy to QA Environment
on:
  push:
    branches: [develop, feature/qa-env-deployment]
  pull_request:
    branches: [develop, feature/qa-env-deployment]
jobs:
  deploy:
    environment:
      name: qa-env
      url: https://serendipity-mk1.herokuapp.com/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.QA_HEROKU_API_KEY}}
          heroku_app_name: "serendipity-mk1"
          heroku_email: "bankless@nonsensecodes.io"
          procfile: "web: yarn qa"
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.QA_DISCORD_TOKEN}}
          HD_DISCORD_OWNER_ID: ${{secrets.QA_DISCORD_OWNER_ID}}
          HD_MONGODB_URI: ${{secrets.QA_MONGODB_URI}}
          HD_NOTION_TOKEN: ${{secrets.QA_NOTION_TOKEN}}
          HD_FAQ_PAGE_ID: ${{secrets.QA_FAQ_PAGE_ID}}

