name: Deploy to Production Environment
on:
    push:
        branches:
          - 'DEGEN'
jobs:
    deploy:
        environment:
            name: production
            url: https://bankless-dao-degen-bot.herokuapp.com/
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.17.0'
            - name: Install dependencies
              run: yarn install
            - name: Prettier Code
              run: yarn format
            - name: Lint Code
              run: yarn lint
            - name: Build and Compile Typescript
              run: yarn build
            - name: Run test cases
              run: yarn test --watchAll=false
            - name: Deploy to Heroku Shared Test Environment
              uses: AkhileshNS/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
                  heroku_app_name: 'bankless-dao-degen-bot'
                  heroku_email: 'bankless@nonsensecodes.io'
                  procfile: 'worker: yarn prod'
              env:
                  HD_DISCORD_BOT_TOKEN: ${{secrets.PROD_DISCORD_TOKEN}}
                  HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.PROD_BOT_PUBLIC_KEY}}
                  HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.PROD_BOT_APPLICATION_ID}}
                  HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
                  HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
                  HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
                  HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
                  HD_NOTION_TOKEN: ${{secrets.PROD_NOTION_TOKEN}}
                  HD_FAQS_PAGE_ID: '29353e63-e864-411a-abc0-061d04906c16'
                  HD_DISCORD_SERVER_ID: '834499078434979890'
                  HD_NOTION_GUEST_PASS_DATABASE_ID: '15fae33760724cf7b696a981d53e50cb'
                  HD_DAO_CURRENT_SEASON: '1'
                  HD_DISCORD_CHANNEL_BOUNTY_BOARD_ID: '850402063741091880'
                  HD_DISCORD_ROLE_GENESIS_SQUAD: '839004775751352341'
                  HD_DISCORD_ROLE_ADMIN_ROLE_ID: '836317754038026241'
                  HD_DISCORD_ROLE_GRANTS_COMITTEE: '860222982416498688'
                  HD_DISCORD_ROLE_LVL_4: '840627393777762344'
                  HD_DISCORD_ROLE_LEVEL_3: '839005209611075614'
                  HD_DISCORD_ROLE_CONTRIBUTORS_LVL_2: '839005084016312360'
                  HD_DISCORD_ROLE_LEVEL_1: '834560235704025108'
                  HD_DISCORD_ROLE_GUEST_PASS: '848369657281773599'
                  HD_DISCORD_ROLE_DEVELOPERS_GUILD: '843924063591727195'
                  HD_DAO_BOUNTY_BOARD_URL: 'https://bountyboard.bankless.community/'
