name: Deploy to Production Environment Legacy V3
on:
  push:
    branches:
      - 'DEGEN-v3'
jobs:
  deploy-degen-legacy-v3:
    environment:
      name: degen-legacy-v3
      url: https://app.logdna.com/273e532689/logs/view?apps=degen-legacy-v3
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Run test cases
        run: yarn test --watchAll=false
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'degen-legacy-v3'
          heroku_email: 'patinobrian@gmail.com'
          procfile: 'worker: yarn prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.DEGEN_LEGACY_V3_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.DEGEN_LEGACY_V3_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.DEGEN_LEGACY_V3_APPLICATION_ID}}
          HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
          HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
          HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
          HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
          HD_LOGDNA_TOKEN: ${{secrets.PROD_LOGDNA_TOKEN}}
          HD_TWITTER_API_TOKEN: ${{secrets.PROD_TWITTER_API_TOKEN}}
          HD_TWITTER_API_SECRET: ${{secrets.PROD_TWITTER_API_SECRET}}
          HD_TWITTER_BEARER_TOKEN: ${{secrets.PROD_TWITTER_BEARER_TOKEN}}
          HD_TWITTER_ACCESS_TOKEN: ${{secrets.PROD_TWITTER_ACCESS_TOKEN}}
          HD_TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.PROD_TWITTER_ACCESS_TOKEN_SECRET}}
          HD_TWITTER_CLIENT_ID: ${{secrets.PROD_TWITTER_CLIENT_ID}}
          HD_TWITTER_CLIENT_SECRET: ${{secrets.PROD_TWITTER_CLIENT_SECRET}}
          HD_POAP_DOMAIN: ${{secrets.PROD_POAP_DOMAIN}}
          HD_POAP_AUDIENCE: ${{secrets.PROD_POAP_AUDIENCE}}
          HD_POAP_CLIENT_ID: ${{secrets.PROD_POAP_CLIENT_ID}}
          HD_POAP_CLIENT_SECRET: ${{secrets.PROD_POAP_CLIENT_SECRET}}
          HD_SENTRY_IO_DSN: ${{secrets.PROD_SENTRY_IO_DSN}}
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          sourcemaps: './dist'
        with:
          environment: 'production'
          version: 'degen@${{ steps.package-version.outputs.current-version }}'
          sourcemaps: './dist'
