name: Deploy to Production Environment Legacy V2
on:
  push:
    branches:
      - 'DEGEN-v2'
jobs:
  deploy-degen-legacy-v2:
    environment:
      name: degen-legacy-v2
      url: https://app.logdna.com/273e532689/logs/view?apps=degen-legacy-v2
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Run test cases
        run: yarn test --watchAll=false
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'degen-legacy-v2'
          heroku_email: 'patinobrian@gmail.com'
          procfile: 'worker: yarn prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.DEGEN_LEGACY_V2_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.DEGEN_LEGACY_V2_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.DEGEN_LEGACY_V2_APPLICATION_ID}}
          HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
          HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
          HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
          HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
          HD_LOGDNA_TOKEN: ${{secrets.PROD_LOGDNA_TOKEN}}
